### ISSUE TITLE
Clinical Onset Picker UI Bugs in Internet Explorer 11

### ISSUE THREAD

**Issue by austenator** [cerner/terra-clinical#601] opened 2019-12-17 22:23 UTC
# Bug Report

## Description
These are screenshots of the onset picker in IE 11. 
<img width="342" alt="Screen Shot 2019-12-17 at 3 12 50 PM" src="https://user-images.githubusercontent.com/21992376/71036584-9e140a80-20e3-11ea-9905-1c852318508d.png">
<img width="342" alt="Screen Shot 2019-12-17 at 3 36 20 PM" src="https://user-images.githubusercontent.com/21992376/71036586-9eaca100-20e3-11ea-8973-f2927ba0f6f9.png">

The first screenshot shows the misalignment of the age fields and that the age number field is missing the increase/decrease buttons.

The second screenshot also shows the misalignment and missing increase  / decrease buttons when the age granularity of Year(s) is selected.

## Steps to Reproduce

1. Open the clinical onset picker in IE 11.
2. Select the Precision of On/At
3. Select the granularity as Age
4. Witness issues.

## Additional Context / Screenshots

See above.

## Expected Behavior

The age fields should be aligned and the increase/decrease buttons should be shown in order to prevent the user entering an impossible age (future age).
## Environment

* Component Name and Version: Clinical Onset Picker 4.10.0
* Browser Name and Version: Internet Explorer 11
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile): Mac

**Comment by emilyrohrbough** [comment] 2019-12-17 22:38
duplicate of https://github.com/cerner/terra-clinical/issues/586

There is a fix out for review: https://github.com/cerner/terra-clinical/pull/596

**Comment by austenator** [comment] 2019-12-18 14:17
@emilyrohrbough That issue deals with the alignment, is there anything out there for the missing increase/decrease buttons I mentioned?

**Comment by emilyrohrbough** [comment] 2019-12-18 14:43
@austenator The spinner control you have asked about is specific to the browser's implementation of a number input. Here is an article that gives more detail: https://css-tricks.com/numeric-inputs-a-comparison-of-browser-defaults/

Looking at terra-ui.com on chrome you will see:
![Screen Shot 2019-12-18 at 8 41 36 AM](https://user-images.githubusercontent.com/14099737/71095495-538d9f00-2172-11ea-801c-8ba2208f7677.png)

and when you hover the number input on chrome you will see:
![Screen Shot 2019-12-18 at 8 41 58 AM](https://user-images.githubusercontent.com/14099737/71095563-71f39a80-2172-11ea-8afe-f924f718e63f.png)


then on Firefox, the spinner control is always face up:
<img width="413" alt="Screen Shot 2019-12-18 at 8 41 42 AM" src="https://user-images.githubusercontent.com/14099737/71095544-6a33f600-2172-11ea-8b57-dc6adf47408a.png">

**Comment by ryanthemanuel** [comment] 2020-01-07 22:23
As @emilyrohrbough mentioned this is a duplicate of #586.  The increment/decrement buttons have been purposefully left to be determined by the browser.  Closing this.

cc @neilpfeiffer

**Closed by ryanthemanuel** 2020-01-07 22:23 UTC
Labels: Orion Reviewed
