### ISSUE TITLE
Onset Picker crashes when birthdate is less than one week ago

### ISSUE THREAD

**Issue by dkschoonover** [cerner/terra-clinical#535] opened 2019-07-22 14:46 UTC
# Bug Report

## Description
When a birthdate prop is set that is less than 1 week ago, the onset control crashes when granularity is set to age.

Error is thrown on this [line](https://github.com/cerner/terra-clinical/blob/ca3e23209461bba0001db7fd4d388497bbe71dfe/packages/terra-clinical-onset-picker/src/OnsetPicker.jsx#L378-L379) because allowedAgeUnits is returning null.

## Steps to Reproduce
1. Set the onset control birthdate prop to less than one week ago.
2. Set the granularity of the control to age.

## Expected Behavior
Control does not crash.

## Possible Solution
The age granularity may not make sense for patients that are less than a week old.  Allowed age units are returned [here](https://github.com/cerner/terra-clinical/blob/ca3e23209461bba0001db7fd4d388497bbe71dfe/packages/terra-clinical-onset-picker/src/OnsetUtils.js#L92-L94) and null is returned.

## Environment

* Component Name and Version: terra-clinical-onset-picker/4.3.0
* Browser Name and Version: All
* Node/npm Version: Node 8/npm 5
* Webpack Version: 4.34.0
* Operating System and version (desktop or mobile): desktop

## @ Mentions
@doogthemushroom, @ryanthemanuel

**Comment by pranav300** [comment] 2019-07-23 08:05
I have found some possible solution. Kindly share your thoughts on them.

1. The function https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-onset-picker/src/OnsetUtils.js#L88 returns null for input less than a week. So, should we include days as well in the check and provide users an option to enter days.

2. We can have a check at the time of render if the difference between the birthdate and current date is less than a week. We can remove the age option from granularity.

3. After the null value is returned should we handle it over here https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-onset-picker/src/OnsetUtils.js#L88?

**Comment by doogthemushroom** [comment] 2019-07-24 14:03
> 1. The function https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-onset-picker/src/OnsetUtils.js#L88 returns null for input less than a week. So, should we include days as well in the check and provide users an option to enter days.

I would consider this a separate change that resolving this bug. Including a day option for the age granularity would likely have the same issue with if the birthdate were only hours old (would likely result in lower fail rates but the issue would still be present). In addition, as a consumer I don't want day support as our backend doesn't support it. This change would necessitate a major version bump imo.

> 2. We can have a check at the time of render if the difference between the birthdate and current date is less than a week. We can remove the age option from granularity.

This solution makes sense to me, but it should also handle the case when the consumer initializes the picker with age granularity and a birthdate that doesn't work with it. Not sure what I'd default to, maybe just clear the granularity selection.

> 3. After the null value is returned should we handle it over here https://github.com/cerner/terra-clinical/blob/master/packages/terra-clinical-onset-picker/src/OnsetUtils.js#L88?

This could return an empty array instead so at least the component doesn't error out... but it would be a little wonky selecting the age granularity and then having no options to choose from. I'd lean towards the second solution.

**Comment by jeremyfuksa** [comment] 2019-10-10 21:12
>  In addition, as a consumer I don't want day support as our backend doesn't support it.
@doogthemushroom, can you give more detail about this? Because this particular case implies a NICU scenario, in which case granularities as small as minutes might be appropriate.

**Comment by ryanthemanuel** [comment] 2019-10-22 14:32
@jeremyfuksa I think the problem is that there is no way to store this as a certain number of days in the database.  I think we'd need to figure out what the expectation is in a NICU case.

**Comment by ryanthemanuel** [comment] 2019-10-22 14:35
@PaulSolDev do you know what the use case would be for an onset picker control if the person is days/hours old rather than a week?

**Closed** 2019-11-04 17:47 UTC
Labels: Needs Orion Requirements, Orion Reviewed, bug
