### ISSUE TITLE
Re-Evaluate the padding implementation on the terra-clinical-detail-view

### ISSUE THREAD

**Issue by deepaksuresh90** [cerner/terra-clinical#611] opened 2020-02-19 08:42 UTC
# Bug Report

## Description
  Using terra-clinical-detail-view which is causing extra padding/spacing surrounded by the component

## Steps to Reproduce
Add a component under an { DetailView } terra-clinical-detail-view

## Additional Context / Screenshots
<img width="1519" alt="Screenshot 2020-02-19 at 1 26 10 PM" src="https://user-images.githubusercontent.com/32136634/74814019-63656300-531c-11ea-8537-1427b56934d2.png">
<img width="477" alt="Mobile View" src="https://user-images.githubusercontent.com/32136634/74814100-9a3b7900-531c-11ea-85eb-597bcdab22a4.png">

## Expected Behavior
The padding/margin space should be minimal 

## Environment

* Component Name and Version:  DetailView  from terra-clinical-detail-view Version 3.11.0 
* Browser Name and Version: Any
* Node/npm Version: [e.g. Node 10/npm 6
* Webpack Version:
* Operating System and version (desktop or mobile): Any

##

**Comment by mrw100** [comment] 2020-02-19 13:17
Our application has the same issue with the terra-clinical-detail-view. While doing some further investigation it turns out that the problem is the DetailView comes with a padding of 1.4285rem and then another 1.4285rem is added from the margin of the title section because we aren't supplying the details array to the DetailView.

**Comment by neilpfeiffer** [comment] 2020-02-25 15:15
After discussing further, the Terra-clinical-detail-view was a very basic starter layout helper template for side panels (detail views), but was not really intended to have complex content beyond a simple title and 1-2 subtitles, or have much wide re-use or sophisticated layout options that help it work well beyond the narrow/small slide-panel size. 

As certain detail views became more complex with very specific layout needs that are similar to the clinical-detail-view header but have the potential to be used in other places, medications is one, clinical results (labs & vitals) are another  -- it seems more appropriate rather than continue to expand the features in the detail-view to provide those layouts, to fork off the multi-ingredient medication display header as it's own component, then simplify the detail-view header to then receive a full node/component as the header element. Then you will have the ability to use the stand-alone internal component as a re-usable header for other pages and modals like this one, including responsive behaviors in the future that better optimize screen/space usage.

(A similar approach will be recommended and planned for the clinical results detail-view header, that is can be it's own component the detail-view can then receive. Related issues are https://github.com/cerner/terra-clinical/issues/449 and https://github.com/cerner/terra-clinical/issues/509)

Closing this request and will update the open issue https://github.com/cerner/terra-clinical/issues/492 to include details from this request.

**Closed** 2020-02-25 15:15 UTC
Labels: Needs Orion Requirements, Orion Reviewed, detail-view
