### ISSUE TITLE
Font size - text gets cut/displayed improperly.

### ISSUE THREAD

**Issue by chaitu9916** [cerner/terra-clinical#579] opened 2019-10-09 20:33 UTC
# Bug Report

## Description
* For higher font-sizes , text in the grid gets cut/hidden/not proper.

## Steps to Reproduce

1. [Terra Clinical DataGrid example](https://engineering.cerner.com/terra-ui/components/terra-clinical-data-grid/clinical-data-grid/datagrid-examples/datagrid-with-selections)
2. Set the body font-size to 30px.

## Additional Context / Screenshots
![image](https://user-images.githubusercontent.com/913956/66517575-fc4fbc00-eaa8-11e9-89a1-d125c3439ef5.png)

## Expected Behavior
* Text is properly displayed

## Environment

* Component: terra-clinical-data-grid and Version:2.12.0
* Browser: Chrome , Version : 79
* MacOS

## @ Mentions

`[](url)`

##Watch
[Kurian, Habel](https://github.cerner.com/hk016213)

**Comment by pranav300** [comment] 2019-10-11 11:01
@chaitu9916

1. The recommended UX pattern is to have base font-size of `14px` for open-source theme and for orion-fusion-theme, it is`12px`.
2. Is there a reason for you to set it to `30px` and have you considered using the default zoom instead?

In my opinion, this may not be a valid issue. @neilpfeiffer @tbiethman any thoughts?

**Comment by habelk** [comment] 2019-10-11 16:39
We dont have a use case of 30 px today. But we were hoping the row height (supplied as rems) for clinical data grid will adjust based on the base font size.

**Comment by ShettyAkarsh** [comment] 2019-10-14 05:18
@neilpfeiffer, @jeremyfuksa  could you guys please confirm is this the valid workflow ?

**Comment by neilpfeiffer** [comment] 2019-10-22 13:45
This is not a valid bug as currently described. There are two issues needing to be corrected: 

1. In order for the rem sizing to correctly cascade and adjust UI elements that are not text -- consumers need to adjust the font-size not on the `body`, but on the `html` element (body should always be set to 1rem). Try it and you will see the data-grid row heights correctly resize (if set to rems not pixels). cc: @chaitu9916 @habelk 

2. Restating for clarity -- someone new to the data-grid may assume that it is a flexible table that should respond to it's content, however, the data-grid is by design a fixed-size-concept component - where it does not respond or grow to its content, but has rigid heights set by the consumer. If a consumer needs larger row heights due to larger content, it is the consumers responsibility to set accordingly. Using rem sizing will allow for both content and row height to appropriately adjust if the html font-size is changed.  (describing this for if any other consumers who might see this and might also be confused)

---
Closing as not an issue.

**Closed by neilpfeiffer** 2019-10-22 13:45 UTC
Labels: Needs design input, Orion Reviewed
